name: Build and Push Frontend Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Thay tên image cho Frontend để không bị đè lên Backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-ltw:latest
      - name: Update Kubernetes manifests
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Clone repo k8s
          git clone https://${{ secrets.GIT_PAT }}@github.com/asbass/k8s.git
          
          # Sửa file deployment.yaml
          # Lệnh sed này sẽ thay thế image sau dấu :
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/ltw:latest|g" k8s/backend/deployment.yaml
          
          # Kiểm tra xem có thay đổi thật sự hay không
          cd k8s
          if [ -n "$(git status --porcelain)" ]; then
            git add backend/deployment.yaml
            git commit -m "Auto-update image tag to ${{ secrets.DOCKERHUB_USERNAME }}/ltw:latest"
            git push
            echo "Đã cập nhật thành công repo k8s!"
          else
            echo "Không có thay đổi nào trong file deployment.yaml, không cần commit."
          fi
